#!/usr/bin/env bash
# ===========================================================================
# LAYER B: turn the WIT world into a WebAssembly Component + typed JS bindings.
#
# Pipeline (all via jco, which bundles wasm-tools):
#   wit/ludens.wit --embed--> core+types --new--> component --transpile--> JS
#
# The GUEST here is jco's `--dummy` implementation of the `ludens` world. It is
# a faithful placeholder for the real guest exactly as toolchain/standin/*.c is
# a placeholder for Mojo: it proves the WIT -> component -> typed-JS path runs
# today. The real guest swaps in when a canonical-ABI core module exists --
# generated by wit-bindgen from the Mojo core once `mojo` can emit IR (STATUS.md).
#
# Output: build/component/ludens.component.wasm  +  build/component/js/*
#   build/component/js/ludens.d.ts               <- typed cross-language contract
#   build/component/js/interfaces/*.d.ts         <- engine (export) + host (import)
#
# Requires network (npm) the first time to fetch jco; skips cleanly if offline.
# ===========================================================================
set -euo pipefail
cd "$(dirname "$0")/.."

JCO="${JCO:-npx --yes @bytecodealliance/jco@latest}"
OUT=build/component
mkdir -p "$OUT"

if ! $JCO --version >/dev/null 2>&1; then
  echo "jco unavailable (offline?). Skipping component build."
  echo "Install: npm i -g @bytecodealliance/jco   (or run with network)."
  exit 0
fi

echo "# 1) embed the ludens world type section (dummy guest placeholder)"
$JCO embed --wit wit/ludens.wit --world-name ludens --dummy -o "$OUT/ludens.core.wasm"

echo "# 2) core module -> WebAssembly Component"
$JCO new "$OUT/ludens.core.wasm" -o "$OUT/ludens.component.wasm"

echo "# 3) Component -> typed JS bindings (this is what the browser host imports)"
$JCO transpile "$OUT/ludens.component.wasm" -o "$OUT/js" --name ludens >/dev/null

echo "OK: component + typed bindings in $OUT/"
echo "    engine (wasm exports): $(grep -oE 'export function [a-zA-Z]+' "$OUT/js/interfaces/ludens-engine-engine.d.ts" | sed 's/export function //' | paste -sd, -)"
echo "    host   (JS implements): $(grep -oE 'export function [a-zA-Z]+' "$OUT/js/interfaces/ludens-engine-host.d.ts" | sed 's/export function //' | paste -sd, -)"
